# Generated by Django 3.2.5 on 2021-08-15 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(max_length=10, unique=True)),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='username')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date_joined')),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
        migrations.CreateModel(
            name='Greade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('std', models.PositiveIntegerField(verbose_name='Grade or Standard')),
                ('subject', models.CharField(max_length=60, verbose_name='Siubject Name')),
                ('topic', models.CharField(max_length=500, verbose_name='Topic')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cover_img', models.URLField(blank=True, default='https://i.picsum.photos/id/1000/5626/3635.jpg')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.greade')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(max_length=100, verbose_name='Father Name')),
                ('father_mobile_no', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Father Mobile Number')),
                ('father_email', models.EmailField(max_length=254, verbose_name='Father Email Id')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.greade')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialHandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=20, verbose_name='Platform Name')),
                ('link', models.URLField(blank=True, default='https://facebook.com')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(blank=True, max_length=10, unique=True)),
                ('session_title', models.CharField(max_length=50, verbose_name='Session Title')),
                ('session_des', models.TextField(blank=True, verbose_name='Description')),
                ('duration', models.DurationField(blank=True, verbose_name='Duration')),
                ('time', models.DateTimeField(verbose_name='Time')),
                ('no_of_student_allowed', models.PositiveIntegerField(blank=True, null=True, verbose_name='No of Students allowed in session')),
                ('price_per_student', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('payment_mode', models.CharField(choices=[('online', 'online'), ('offline', 'offline')], default='online', max_length=20)),
                ('custom_session', models.BooleanField(default=False, verbose_name='Negotiation')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.greade')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Last Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, verbose_name='Gender')),
                ('profile_img', models.URLField(blank=True, default='https://picsum.photos/seed/picsum/200/300')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Address')),
                ('description', models.TextField()),
                ('dob', models.DateField(null=True, verbose_name='Date Of Birth')),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='BankAccont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank Name')),
                ('iban', models.CharField(max_length=30, verbose_name='IBAN Number')),
                ('bank_address', models.CharField(max_length=255, verbose_name='Bank Address')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher')),
            ],
        ),
    ]
